Section "ServerLayout"
  Identifier "layout"
  Screen 0 "nvidia"
  Inactive "bochs"
EndSection

Section "Device"
  Identifier "nvidia"
  Driver "nvidia"
  BusID "PCI:0:6:0"
EndSection

Section "Screen"
  Identifier "nvidia"
  Device "nvidia"
  Option "AllowEmptyInitialConfiguration"
EndSection

Section "Device"
  Identifier "bochs"
  Driver "modesetting"
  BusID "PCI:0:3:0"
EndSection

Section "Screen"
  Identifier "bochs"
  Device "bochs"
EndSection
